"""SOAP note structure enforcer."""

from ai_health_guide.models.report import SOAPNote
from ai_health_guide.models.clinical import TriageColor


def validate_soap(note: SOAPNote) -> list[str]:
    """Validate that a SOAP note contains all required sections.

    Returns a list of validation issues (empty means valid).
    """
    issues = []
    if not note.subjective.strip():
        issues.append("SOAP Subjective section is empty.")
    if not note.objective.strip():
        issues.append("SOAP Objective section is empty.")
    if not note.assessment.strip():
        issues.append("SOAP Assessment section is empty.")
    if not note.plan.strip():
        issues.append("SOAP Plan section is empty.")
    if not note.red_flags_summary and note.triage_color == TriageColor.RED:
        issues.append("SOAP Assessment must list red flags when triage is RED.")
    return issues


def format_soap_markdown(note: SOAPNote) -> str:
    """Render a SOAPNote as a markdown-formatted clinician document."""
    red_flags_text = "\n".join(f"- {rf}" for rf in note.red_flags_summary) or "None detected."
    triage_badge   = {"RED": "🔴 RED — EMERGENCY", "YELLOW": "🟡 YELLOW — URGENT", "GREEN": "🟢 GREEN — NON-URGENT"}

    return f"""# AI Health Guide — Clinician Report
**Triage Level:** {triage_badge.get(note.triage_color, note.triage_color)}
**Patient Language:** {note.patient_language}
**Report Language:** {note.language}

---

## S — Subjective
{note.subjective}

## O — Objective
{note.objective}

## A — Assessment
{note.assessment}

**Red Flags Detected:**
{red_flags_text}

## P — Plan
{note.plan}

---
*This report was generated by AI Health Guide for clinical reference only.*
"""
